version: "3.8"
services:
  activemq:
    image: rmohr/activemq
    container_name: jms-activemq
    ports:
       - "61616:61616"
       - "8161:8161"
       - "5762:5762"
    healthcheck:
      test: ["CMD-SHELL", "curl -u admin:admin -k -f http://localhost:8161/admin"]
      interval: 10s
      timeout: 3s
      retries: 20

  client:
    build: ../converter-jms-client/
    environment:
      INPUT_DIR: "data1/input"
      OUTPUT_DIR: "data1/output"
      BROKER_URL: "tcp://jms-activemq:61616"
      BROKER_USERNAME: "admin"
      BROKER_PASSWORD: "admin"
    container_name: jms-client
    volumes:
      - ../../temp/data:/usr/app/data1
    depends_on:
      activemq:
        condition: service_healthy
        
  server:
    build: ../converter-jms/
    container_name: jms-server
    environment:
      BROKER_URL: "tcp://jms-activemq:61616"
      BROKER_USERNAME: "admin"
      BROKER_PASSWORD: "admin"
    depends_on:
      activemq:
        condition: service_healthy